(package "dashboard-bm"
         "0.0.1"
         "Visual Bookmarks for Dashboard")

(website-url "https://github.com/emacs-dashboard/dashboard-bm")
(keywords "tools")

(package-file "dashboard-bm.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "dashboard")
(depends-on "bm")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
